In [1]:
import pandas as pd
import io
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("Churn_Modelling.csv")
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
X=data.iloc[:,:-1].values
X

array([[1, 15634602, 'Hargrave', ..., 1, 1, 101348.88],
       [2, 15647311, 'Hill', ..., 0, 1, 112542.58],
       [3, 15619304, 'Onio', ..., 1, 0, 113931.57],
       ...,
       [9998, 15584532, 'Liu', ..., 0, 1, 42085.58],
       [9999, 15682355, 'Sabbatini', ..., 1, 0, 92888.52],
       [10000, 15628319, 'Walker', ..., 1, 0, 38190.78]],
      shape=(10000, 13), dtype=object)

In [5]:
y=data.iloc[:,-1].values
y

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [6]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [8]:
data.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [9]:
data = data.drop(['Surname', 'Geography','Gender'], axis=1)

In [10]:
data.head()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0

In [14]:
scaler=MinMaxScaler()
df1=pd.DataFrame(scaler.fit_transform(data))
print(df1)

          0         1      2         3    4         5         6    7    8   \
0     0.0000  0.275616  0.538  0.324324  0.2  0.000000  0.000000  1.0  1.0
1     0.0001  0.326454  0.516  0.310811  0.1  0.334031  0.000000  0.0  1.0
2     0.0002  0.214421  0.304  0.324324  0.8  0.636357  0.666667  1.0  0.0
3     0.0003  0.542636  0.698  0.283784  0.1  0.000000  0.333333  0.0  0.0
4     0.0004  0.688778  1.000  0.337838  0.2  0.500246  0.000000  1.0  1.0
...      ...       ...    ...       ...  ...       ...       ...  ...  ...
9995  0.9996  0.162119  0.842  0.283784  0.5  0.000000  0.333333  1.0  0.0
9996  0.9997  0.016765  0.332  0.229730  1.0  0.228657  0.000000  1.0  1.0
9997  0.9998  0.075327  0.718  0.243243  0.7  0.000000  0.000000  0.0  1.0
9998  0.9999  0.466637  0.844  0.324324  0.3  0.299226  0.333333  1.0  0.0
9999  1.0000  0.250483  0.884  0.135135  0.4  0.518708  0.000000  1.0  0.0

            9    10
0     0.506735  1.0
1     0.562709  0.0
2     0.569654  1.0
3     0.469120  0.0
4     0.395400  0.0
...        ...  ...
9995  0.481341  0.0
9996  0.508490  0.0
9997  0.210390  1.0
9998  0.464429  1.0
9999  0.190914  0.0

[10000 rows x 11 columns]

In [15]:
X_train ,X_test ,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [16]:
X_train

array([[5344, 15578238, 'Calabrese', ..., 1, 0, 193305.35],
       [8774, 15589200, 'Madukaife', ..., 1, 0, 118749.58],
       [2198, 15670753, 'Uvarova', ..., 1, 1, 31302.35],
       ...,
       [7643, 15654760, 'Su', ..., 1, 1, 121765.0],
       [8229, 15632609, 'Burdekin', ..., 1, 0, 32824.15],
       [1424, 15589221, 'Kennedy', ..., 1, 1, 23317.88]],
      shape=(8000, 13), dtype=object)

In [17]:
X_test

array([[6775, 15569432, 'Macleod', ..., 1, 1, 85240.61],
       [4743, 15762134, 'Liang', ..., 1, 1, 170679.74],
       [1418, 15774166, 'Mitchell', ..., 0, 1, 127560.77],
       ...,
       [5771, 15694381, 'Lloyd', ..., 1, 0, 171587.9],
       [7859, 15764726, 'Kerr', ..., 0, 1, 5791.85],
       [7066, 15568162, 'Sung', ..., 1, 1, 51711.57]],
      shape=(2000, 13), dtype=object)

In [18]:
print("Lenght of X_test ",len(X_test))

Lenght of X_test  2000